export default {
  PRODUCT_START: "PRODUCT_START",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAILURE: "PRODUCT_FAILURE",

  BRAND_START: "BRAND_START",
  BRAND_SUCCESS: "BRAND_SUCCESS",
  BRAND_FAILURE: "BRAND_FAILURE",

  WOODS_START: "WOODS_START",
  WOODS_SUCCESS: "WOODS_SUCCESS",
  WOODS_FAILURE: "WOODS_FAILURE",

  FILE_UPLOAD_START: 'FILE_UPLOAD_START',
  FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS',
  FILE_UPLOAD_FAILURE: 'FILE_UPLOAD_FAILURE'
};